language: node_js
node_js:
  - "7"
sudo: false
branches:
  only:
    - master
env:
  global:
    - secure: "0j+ZdrnknEh89pR+Vie7ZXPhTxJtRJli+8bMaP8jC+YVX//Y0R55BwOqYCCZ6DR9nfyisVyZ80b8fYDkloPa87Nhle8ByFNKNE5ifOnETVymp3O420bS9BcBlExPD00dktPgc+Z1bFj1+EhQys/5f5uYZDzinty+Jf04CjZj1cAVlA2ICUyD7+OONjTayE7sIq6jYPivhFPSwIB7XF+bdcuPFVHmsfqcpO/UN6nNFHYXBinvIn279PISokBKg95EaFhJbXunWeD3JiPucbAEAtGDOF5BqvkIs+BLL7jyAzWDQFwNZSIPhxhFn1eOIr0sKz5CaOxNgI/bnd0ihiJ50GSTl9vrzAflhg8S0Xjdb3sGkTGTc0ZsQREoht34UebuSo0zn25ilQHiIABkk2n4JXCGfXpDI0aW1vPx0JPkk/PorRNcHoaP2ByTUeW8LPHGWyaHeuIs3ZEDAtVeyi9VSIH9uJ6nEstSbJZGNs1NOfXVBQhxg/QDbT/MU0rNZrJ9JP4dKgwogI6UmVCWIMp+Av4C9T2f8pdMKz7dUxakFCuonVXeqQ1aiS9L92eG8Z1jgw4BTZinDxML+ajCbgW3rKq7rw52Bfw+abNHsRHxRyRctUKxS2hsC/pDbDhiTiDzlqw5nSNcUQBh6+G+Y1ONhx+aokEzz5yoeMeGShb4LgA="
    - secure: "vh5ZWWn/p+icAJBJTr0a9wY3exYtUheihZNDkptLUofV9yKPn37EdAnqBA3RXvjDTpwQNWo9d7MsRSov2NqoAUsN8VWfmTVlEEA5DJm7pd7cuwDM8FPQ9iugjIGG/CIPYNnR7/NS5PAfPPB2OfCv5ZhBBzK9BVGqnXCF1+eKzj3wDGaAKjv3hcjp4cI1ZnX7gEE2l0v/NqJ7mzZJgVyrvRxraV+iVk6PiPfnvh16db64qZmBclcz1nRqEtsbgN3pXWXUBTf/jyk28EqiBowYn+P083rruu4+KRNfYpGAOoBA1GbpUygEDoLccJiWI151YCUweGOsraNBVPrhA8J6YnB6zoU2FBIaBqDWt/j7bGrTaW2v5OELQal8m+znAVECLwSXbItUuxKLKR+eaTUO8HVz6dw8hyXBxlwS/FJ9f1si3M10QWJ5IDKF2r7XW0A8upAuwdeLjdKt7Wnu9WbtpRqJB+liEK9FfZs4whBBAGSSV1lFPyi7X1SFuoB99LYGQ151gFjMs0+htOYkpysjTZJYp2KFv7W9G9Qj2CDhWgNNXKQXuGF/fUoCnmoFdkiJYrHyhWoVT27/QLAsS9kTeBwkTLlnXB7d7NBR2RY2ly/kcWJhXBO7Ciqkc3ZT5kCxqWO+zT21iNoCz90OmzVpZs3KsfZ9W2Qa9ivNMbQnZW8="
    - DEPLOY_PATH=/var/www/node/crs
addons:
    ssh_known_hosts:
      - vps.noob.tw
    apt:
      packages:
        - sshpass
before_script:
  - npm install -g eslint-config-airbnb-base eslint-plugin-import eslint
script:
  - eslint --fix server.js
after_success:
  - tar -czf package.tar.gz --exclude='.git' --exclude='./node_modules' *
  - export SSHPASS=$SERVER_PASS
  - sshpass -e scp package.tar.gz Noob@$SERVER_HOST:$DEPLOY_PATH
  - sshpass -e ssh Noob@$SERVER_HOST "cd /var/www/node/crs; tar -xzf package.tar.gz; rm package.tar.gz; npm install; echo Fine. Deployed.;"
cache:
  directories:
   - node_modules